name: Publish Release
on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: install frontend dependencies
        run: pnpm install --ignore-workspace --no-frozen-lockfile

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v1.0.8-patched
          releaseName: 'Splicerr v1.0.8-patched'
          releaseBody: 'Fixed Splice GraphQL API Apollo headers.'
          releaseDraft: true
          prerelease: false
          args: --ignore-workspace
